# Generated by Django 4.2.6 on 2024-02-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='token',
            field=models.FloatField(default=0),
        ),
    ]
