# Generated by Django 4.2.6 on 2024-02-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_item_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='token',
        ),
    ]
